version: '3'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
  db:
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres